# CS 237  Tutorial on Numpy

Numpy is a Python library which provides high-performance multi-dimension arrays for
scientific computing and data science.  It also provides a full set of
mathematical, especially probability, functions, which can be
applied to single values or entire arrays.  We will use it throughout the
course, and in fact I recommend that you use it in place of the standard <code>math</code>
library. 

NOTE:  Although numpy provides extensive functionality for multi-dimensional arrays, we
will only use 1-D arrays, which look pretty much list normal Python lists. 

For more information about Numpy (and Python), check out this notebook, from which
I draw some of the information in this notebook:

https://github.com/kuleshov/cs228-material/blob/master/tutorials/python/cs228-python-tutorial.ipynb


In [147]:
# Here are some imports which will be used in code that we write for CS 237

# Imports used for the code in CS 237

import numpy as np                # arrays and functions which operate on array, plus math functions


## Numpy Arrays

Numpy provides an (multi-dimensional) array type, <code>ndarray</code>but we will only need them in the 1-D case,
so we just want to understand how normal Python lists and numpy arrays work, and how to
integrate numpy arrays into our Python programming. 

For further information, see the manual page:  


### Basic One-Dimensional Arrays

The numpy library functions return arrays instead of normal Python lists. Since
numpy automatically converts normal lists into numpy arrays, we can use lists
without any problems.  

However, the reverse is not true:  normal Python functions which expect lists will NOT
work with numpy arrays, and you'll have to make adjustments. 

In [148]:
# Creating a numpy array from a list

ex1 = np.array( [ 12,3,-3 ] )
print(ex1)

[12  3 -3]


Notice that numpy arrays are printed WITHOUT commas!  That is not actually the internal representation,
which you can see if you simply type the variable on a line by itself. 

In [149]:
ex1

array([12,  3, -3])

In [150]:
# Turning a numpy 1-D array into a list

ex2 = list( ex1 )
print(ex2)

# Or:

e3 = ex1.tolist()
print(e3)

[12, 3, -3]
[12, 3, -3]


In [151]:
ex2

[12, 3, -3]

All the normal slices and access methods from lists will work with numpy arrays, so you don't have to
care about whether they are arrays or lists:

In [152]:
ex1[2]

-3

In [153]:
ex1[:2]

array([12,  3])

### Useful Numpy functions to create useful lists

In [154]:
# Create a list of 0's

np.zeros(5)       #  <- the size of the result must be given

array([0., 0., 0., 0., 0.])

In [155]:
# Create a list of 1's
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [156]:
# Create a list of constant values
np.full(10,3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

### Creating lists in a given range

In [157]:
# Normal Python ranges - they are evaluated lazily by Python, so must turn them into lists to see....

print(  list(range(10))  )

print(  list(range(1,7))  )

print(  list(range(2,12,2))  )

print(  list(range(12,2, -3)) )

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6]
[2, 4, 6, 8, 10]
[12, 9, 6, 3]


In [158]:
# Numpy ranges -- same except spelled with an 'a'

print(  list(  np.arange(10)  )  )

print(  list(  np.arange(1,7)  )  )

print(  list(  np.arange(2,12,2)  )  )

print(  list(  np.arange(12,2, -3)  ) )

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6]
[2, 4, 6, 8, 10]
[12, 9, 6, 3]


In [159]:
# BUT also worked with floating point, but you'll get the usual weirdness with floating-point values

ex4 = list( np.arange(0.0,1.0,0.1) ) 

print(ex4)
print()
# If you want to print this out with less precision, you can round 
ex4b = np.around( ex4, 1 )            

print( ex4b )

[0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [160]:
# Linear spacing in a range

# The linspace function does the same thing as the previous, but it allows you
# to specify HOW MANY values, not the increment

# NOTE: Unlike range, the upper bound is inclusive (it will be one of the values)

print( np.linspace(0,1,10) )   
print()
print( np.linspace(0,1,11) )    

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Useful array functions returning a scalar

In [161]:
# Here are functions that take a list or array as input and produce a scalar value

ex6 = np.array( [ 2,4,3,6,5,3,7, 2 ])

print(  np.size(ex6)   )                # Number of elements in array, same as len(...) on lists

print(  np.amax(ex6)  )                 # Note the 'a' added to front for "array max"

print(  np.amin(ex6)  )                 # Ditto 

print(  np.mean(ex6)  )                 # Find the mean (average) of the array

print(  np.sum(ex6)   )                  # sum of all members of list or array

print(  np.prod(ex6)   )                 # product -- note that the input is a list

print(  np.argmax(ex6)  )                # find the index of the max element

print(  np.argmin(ex6)  )                # find the index of the min elemnt


8
7
2
4.0
32
30240
6
0


### Useful array functions to return another array

In [162]:
# Here are some array processing functions, they take an array and output an array

# Sorting   (in place -- changes the array permanently)

print(ex1)

ex1.sort()

print(ex1)
print()

# eliminate duplicate values (sorts it as well!)

ex5 = np.array( [ 13,7,5,3,4,5,2,3,4 ])

print(  np.unique( ex5 ))

# 

[12  3 -3]
[-3  3 12]

[ 2  3  4  5  7 13]


In [163]:
# It is permanently changed!
print(ex1)

[-3  3 12]


In [164]:
# Finding the indices of a given element in the array

ex5 = np.array( [2,4,3,5,4,3,4]  )
np.where(ex5 == 3)[0]                  # This syntax is weird!

array([2, 5])

## Numpy Math

Numpy provides a complete set of mathematical functions which you should get used
to using. Here is a catalog of useful functions with examples of use.

One of the most useful features of Numpy functions is that they allow you to give
numpy arrays or just Python lists, and it applies the function to every member
of the list.   Numpy will manage as gracefully as possible if you give it
normal lists instead of numpy arrays. For the math functions, we will simply
show how to use them with normal Python lists. 

For further information, see the manual page:   https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

### Basic Math Constants: Pi and E (base of natrual algorithms)



In [165]:
print( 'Pi:', np.pi )

print( 'e:', np.e    )

Pi: 3.141592653589793
e: 2.718281828459045


### Trig Functions: Sin and Cos

In [166]:
ex1 = np.sin( 2.1 )

ex2 = np.sin(  [ 2.3423, 5.4, 1.2324, -5.2435 ] )

print( ex1 )
print( ex2 )

0.8632093666488738
[ 0.7168631  -0.77276449  0.94328826  0.86224488]


### Rounding, truncating, ceiling, floor, absolute value

In [167]:
# Rounding

print(np.around(np.pi))                # Notice the spelling starting with 'a' for "array round"
print(np.around(ex2, 1))
print(np.around(ex2, 3))
print()

# Truncation

print(np.trunc(np.pi))               
print(np.trunc(ex2))
print()

# Ceiling

print(np.ceil(np.pi))           
print(np.ceil(ex2))
print()

# Floor

print(np.floor(np.pi))             
print(np.floor(ex2))

# Absolute value

print(np.absolute(np.pi))             
print(np.absolute(ex2))

3.0
[ 0.7 -0.8  0.9  0.9]
[ 0.717 -0.773  0.943  0.862]

3.0
[ 0. -0.  0.  0.]

4.0
[ 1. -0.  1.  1.]

3.0
[ 0. -1.  0.  0.]
3.141592653589793
[0.7168631  0.77276449 0.94328826 0.86224488]


### Logs and Powers

In [168]:

# Raising to a power -- same as (np.pi ** 5)

print( np.power(np.pi, 10) )                
print()

# calculate exponential  e^x   -- same as  np.e ** x

print( np.exp(10) )       # (e^10)         
print()

# sqs and sqrts

print( np.sqrt(2))
print( np.square(34))
print()

# calculate logs to various bases

print( np.log(10) )       # log to base e      
print()

# calculate natural log (to base e)

print( np.log2(10) )       # log to base 2     
print()

# calculate natural log (to base e)

print( np.log10(10) )       # log to base 10      
print()

93648.04747608298

22026.465794806718

1.4142135623730951
1156

2.302585092994046

3.321928094887362

1.0



### Basic Statistical functions


In [169]:
# Mean or average

ex7 = [2,4,3,6,4,5]

print( np.mean(ex7) )         
print()

# Standard deviation

print( np.std(ex7) )       # log to base 2     
print()

print( np.var(ex7) )       # log to base 2     
print()

print( np.median(ex7) )       # log to base 2     
print()

4.0

1.2909944487358056

1.6666666666666667

4.0

